language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x86-android-23
before_install:
 - chmod +x gradlew
